/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Libro;

/**
 *
 * @author ALY
 */

import Categoria.CategoriaView;
import Libro.LibroController;
import Prestamo.PrestamoView;
import Usuario.UsuarioView;
import bibliotecaapp.DatabaseConnection;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LibroView extends javax.swing.JFrame {

     Connection conexion = null;
    /**
     * Creates new form LibroView
     */
    public LibroView() {
        initComponents();
        ListarLibros();
        R1.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        E1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        E2 = new javax.swing.JPanel();
        P1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        P5 = new javax.swing.JLabel();
        R3 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        R5 = new javax.swing.JTextField();
        R4 = new javax.swing.JTextField();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        P6 = new javax.swing.JLabel();
        R6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        E1.setBackground(new java.awt.Color(153, 153, 255));
        E1.setForeground(new java.awt.Color(255, 255, 255));

        TITULO.setBackground(new java.awt.Color(153, 153, 255));
        TITULO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TITULO.setForeground(new java.awt.Color(0, 0, 0));
        TITULO.setText("Libro");

        javax.swing.GroupLayout E1Layout = new javax.swing.GroupLayout(E1);
        E1.setLayout(E1Layout);
        E1Layout.setHorizontalGroup(
            E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(E1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(881, Short.MAX_VALUE))
        );
        E1Layout.setVerticalGroup(
            E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(E1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(E1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(E1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        E2.setBackground(new java.awt.Color(204, 204, 255));
        E2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Del Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        E2.setForeground(new java.awt.Color(0, 0, 0));

        P1.setBackground(new java.awt.Color(153, 153, 255));
        P1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        P1.setForeground(new java.awt.Color(0, 0, 0));
        P1.setText("Id:");

        P2.setBackground(new java.awt.Color(153, 153, 255));
        P2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        P2.setForeground(new java.awt.Color(0, 0, 0));
        P2.setText("Titulo:");

        P3.setBackground(new java.awt.Color(204, 204, 255));
        P3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        P3.setForeground(new java.awt.Color(0, 0, 0));
        P3.setText("Autor:");

        P4.setBackground(new java.awt.Color(204, 204, 255));
        P4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        P4.setForeground(new java.awt.Color(0, 0, 0));
        P4.setText("Editorial:");

        P5.setBackground(new java.awt.Color(204, 204, 255));
        P5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        P5.setForeground(new java.awt.Color(0, 0, 0));
        P5.setText("Año De Publicacion:");

        R3.setBackground(new java.awt.Color(204, 204, 255));
        R3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        R3.setForeground(new java.awt.Color(0, 0, 0));
        R3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });

        R2.setBackground(new java.awt.Color(204, 204, 255));
        R2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        R2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));

        R1.setBackground(new java.awt.Color(204, 204, 255));
        R1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        R1.setForeground(new java.awt.Color(0, 0, 0));
        R1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        R1.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        R5.setBackground(new java.awt.Color(204, 204, 255));
        R5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        R5.setForeground(new java.awt.Color(0, 0, 0));
        R5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5ActionPerformed(evt);
            }
        });

        R4.setBackground(new java.awt.Color(204, 204, 255));
        R4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        R4.setForeground(new java.awt.Color(0, 0, 0));
        R4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));

        B1.setBackground(new java.awt.Color(153, 153, 255));
        B1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        B1.setForeground(new java.awt.Color(0, 0, 0));
        B1.setText("Crear");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(153, 153, 255));
        B2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        B2.setForeground(new java.awt.Color(0, 0, 0));
        B2.setText("Seleccionar");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(153, 153, 255));
        B3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        B3.setForeground(new java.awt.Color(0, 0, 0));
        B3.setText("Actualizar");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(153, 153, 255));
        B4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        B4.setForeground(new java.awt.Color(0, 0, 0));
        B4.setText("Eliminar");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Autor", "Editorial", "Titulo", "Año De Publicacion", "Isbn"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        B5.setBackground(new java.awt.Color(153, 153, 255));
        B5.setForeground(new java.awt.Color(0, 0, 0));
        B5.setText("Gestionar Usuario");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(153, 153, 255));
        B6.setForeground(new java.awt.Color(0, 0, 0));
        B6.setText("Gestionar Prestamo");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(153, 153, 255));
        B7.setForeground(new java.awt.Color(0, 0, 0));
        B7.setText("Gestionar Categoria");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        P6.setBackground(new java.awt.Color(204, 204, 255));
        P6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        P6.setForeground(new java.awt.Color(0, 0, 0));
        P6.setText("Isbn:");

        R6.setBackground(new java.awt.Color(204, 204, 255));
        R6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        R6.setForeground(new java.awt.Color(0, 0, 0));
        R6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout E2Layout = new javax.swing.GroupLayout(E2);
        E2.setLayout(E2Layout);
        E2Layout.setHorizontalGroup(
            E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(E2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B7, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(E2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(P5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(P4)
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(P6))
                .addGap(18, 18, 18)
                .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(E2Layout.createSequentialGroup()
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(E2Layout.createSequentialGroup()
                        .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(E2Layout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(R1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addContainerGap(689, Short.MAX_VALUE)))
        );
        E2Layout.setVerticalGroup(
            E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(E2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(E2Layout.createSequentialGroup()
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P1)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(E2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P3)
                            .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P4)
                            .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P2)
                            .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(E2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(E2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P5)
                            .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P6)
                            .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(E2Layout.createSequentialGroup()
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(E2Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(501, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(E2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void ListarLibros()
    {
         try {
             conexion = DatabaseConnection.getConnection();
              LibroDAO modeloLibro = new LibroDAO(conexion);
               
             LibroController controller = new LibroController(modeloLibro);
             conexion = DatabaseConnection.getConnection();
             List<Libro> listaLibros = controller.listarLibros();
             
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.setRowCount(0); // Limpiar la tabla antes de añadir nuevos datos

        for (Libro libro : listaLibros) {
          Object[] row = {libro.getId(), libro.getTitulo(), libro.getAutor(), libro.getEditorial(), libro.getAnioPublicacion(),libro.getIsbn()};
          model.addRow(row);
        }
             
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(LibroView.class.getName()).log(Level.SEVERE, null, ex);
         }
    } 
    
    public void LimpiarCampos()
    {
    
       R1.setText("");
       R2.setText("");
       R3.setText("");
       R4.setText("");
       R5.setText("");
       R6.setText("");
    }
    
    
    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
       
    String titulo = R2.getText();
    String autor = R3.getText();
    String editorial = R4.getText();
    int anioPublicacion = Integer.parseInt(R5.getText());
    String isbn = R6.getText();
    
         try {
             conexion = DatabaseConnection.getConnection();
              LibroDAO modeloLibro = new LibroDAO(conexion);
               
             LibroController controller = new LibroController(modeloLibro);
             controller.crearLibro(titulo, autor, editorial, anioPublicacion,isbn);
            ListarLibros();
            LimpiarCampos();
             
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(LibroView.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
     int filaSeleccionada = jTable1.getSelectedRow();
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Obtener datos de la fila seleccionada
    Object id = model.getValueAt(filaSeleccionada, 0);  // Suponiendo que la columna 0 es el ID
    Object titulo = model.getValueAt(filaSeleccionada, 1);  // Suponiendo que la columna 1 es el título
    Object autor = model.getValueAt(filaSeleccionada, 2);  // Suponiendo que la columna 2 es el autor
    Object editorial = model.getValueAt(filaSeleccionada, 3);  // Suponiendo que la columna 3 es la editorial
    Object anioPublicacion = model.getValueAt(filaSeleccionada, 4);  // Suponiendo que la columna 4 es el año de publicación
    Object isbn = model.getValueAt(filaSeleccionada, 5);  // Suponiendo que la columna 4 es el año de publicación

    
    // Mostrar los datos en los campos de edición
    R1.setText(id.toString());  // R1 es un JTextField donde se muestra el ID
    R2.setText(titulo.toString());  // R2 es un JTextField donde se muestra el título
    R3.setText(autor.toString());  // R3 es un JTextField donde se muestra el autor
    R4.setText(editorial.toString());  // R4 es un JTextField donde se muestra la editorial
    R5.setText(anioPublicacion.toString());  // R5 es un JTextField donde se muestra el año de publicación
    R6.setText(isbn.toString());  // R5 es un JTextField donde se muestra el año de publicación
    
    B1.setEnabled(false);
    
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
    
    int id = Integer.parseInt(R1.getText());
    String titulo = R2.getText();
    String autor = R3.getText();
    String editorial = R4.getText();
    int anioPublicacion = Integer.parseInt(R5.getText());
    String isbn = R6.getText();
    
         try {
             conexion = DatabaseConnection.getConnection();
              LibroDAO modeloLibro = new LibroDAO(conexion);
               
             LibroController controller = new LibroController(modeloLibro);
             controller.ActualizarLibro(id,titulo, autor, editorial, anioPublicacion,isbn);
             ListarLibros();
             B1.setEnabled(false);
             LimpiarCampos();
             
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(LibroView.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
    
    int id = Integer.parseInt(R1.getText());
    String titulo = R2.getText();
    String autor = R3.getText();
    String editorial = R4.getText();
    int anioPublicacion = Integer.parseInt(R5.getText());
    String isbn = R6.getText();
    
         try {
             conexion = DatabaseConnection.getConnection();
             LibroDAO modeloLibro = new LibroDAO(conexion);
               
             LibroController controller = new LibroController(modeloLibro);
             controller.eliminarLibro(id);
             ListarLibros();
             B1.setEnabled(true);
             LimpiarCampos();
             
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(LibroView.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
          dispose(); 
          UsuarioView u = new UsuarioView ();
          u.setVisible(true);
          

    }//GEN-LAST:event_B5ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
         dispose(); 
         CategoriaView u = new CategoriaView();
         u.setVisible(true);
    }//GEN-LAST:event_B7ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
         dispose(); 
         PrestamoView u = new PrestamoView();
         u.setVisible(true);
    }//GEN-LAST:event_B6ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3ActionPerformed

    private void R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton B1;
    public javax.swing.JButton B2;
    public javax.swing.JButton B3;
    public javax.swing.JButton B4;
    public javax.swing.JButton B5;
    public javax.swing.JButton B6;
    public javax.swing.JButton B7;
    private javax.swing.JPanel E1;
    public javax.swing.JPanel E2;
    public javax.swing.JLabel P1;
    public javax.swing.JLabel P2;
    public javax.swing.JLabel P3;
    public javax.swing.JLabel P4;
    public javax.swing.JLabel P5;
    public javax.swing.JLabel P6;
    public javax.swing.JTextField R1;
    private javax.swing.JTextField R2;
    public javax.swing.JTextField R3;
    public javax.swing.JTextField R4;
    public javax.swing.JTextField R5;
    public javax.swing.JTextField R6;
    public javax.swing.JLabel TITULO;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
